version: "3"
networks:
  app-network:
    driver: host

volumes:
  volume-mysql:

services:
  test-app:
    depends_on:
      - database-mysql
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "service:database-mysql"
    image: test-app
    environment:
#      - DATABASE_HOST=database-mysql
#      - DATABASE_USER=root
#      - DATABASE_PASSWORD=root123
#      - DATABASE_NAME=finnplay
#      - DATABASE_PORT=3307
      SPRING_DATASOURCE_URL: jdbc:mysql://spring-test_app-network:3308/finnplay?serverTimezone=UTC&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
    container_name: container-app
    ports:
      - "8090:8080"
#    networks:
#      - app-network


  database-mysql:
    image: mysql:5.7
    container_name: container-mysql
#    network_mode: "service:test-app"

    tty: true
    restart: unless-stopped
    volumes:
      - volume-mysql:/var/lib/mysql
#      - ./dump.sql:/docker-entrypoint-initdb.d/1-dump.sql
    ports:
      - "3308:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root123
      - MYSQL_DATABASE=finnplay
      - TZ=UTC
    networks:
      - app-network